---
- name: Install and configure a web server on port 80
  hosts: self
  become: true
  tasks:
    - name: Update package repository
      apt:
        update_cache: yes

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Configure Nginx to serve on port 80
      copy:
        dest: /etc/nginx/sites-available/default
        content: |
          server {
              listen 80;
              server_name localhost;

              location / {
                  root /var/www/html;
                  index index.html;
              }
          }
      notify: restart nginx

    - name: Create web root directory
      file:
        path: /var/www/html
        state: directory
        owner: www-data
        group: www-data
        mode: '0755'

    - name: Create index.html with Hello, World!
      copy:
        dest: /var/www/html/index.html
        content: |
          <!DOCTYPE html>
          <html>
          <head>
              <title>Welcome</title>
          </head>
          <body>
              <h1>Hello, World!</h1>
          </body>
          </html>
        owner: www-data
        group: www-data
        mode: '0644'

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted
