---
- name: Set up a web server on Amazon Linux
  hosts: localhost
  become: yes
  tasks:
    - name: Remove firewalld
      yum:
        name: firewalld
        state: absent

    - name: Enable the httpd_can_network_connect boolean for SELinux
      seboolean:
        name: httpd_can_network_connect
        state: yes
        persistent: yes

    - name: Install Apache (httpd) on Amazon Linux
      yum:
        name: httpd
        state: present

    - name: Start the Apache service
      service:
        name: httpd
        state: started
        enabled: yes

    - name: Create a sample HTML page
      copy:
        content: "<html><body><h1>Welcome to the web server!</h1></body></html>"
        dest: /var/www/html/index.html
        mode: '0644'

    - name: Ensure the Apache service is running
      service:
        name: httpd
        state: restarted
